Repository aleemer/Internify, pull requests merged in 2021-08, with the labels that each got.

#82 Update to README
  README.md
Labels: documentation, ready for review

#86 Feat/in 94 checkbox state
  client/src/components/molecules/ApplicantDetails.js
  client/src/components/molecules/InputFormJobHeader.js
  client/src/components/molecules/PositionSubHeader.js
  client/src/components/molecules/RadioButtonsGroup.js
  client/src/components/molecules/TechStack.js
  client/src/components/pages/CreateJobPosting/CreateJobHeader.js
  client/src/components/pages/CreateJobPosting/JobDetail.js
  client/src/components/pages/CreateJobPosting/TechRequirements.js
  client/src/components/pages/styles/Profile.css
Labels: feature, ready for review

#85 [IN-108] Update Edit Modal to include more fields to update user
  client/src/components/molecules/EditModal.js
  client/src/components/pages/Profile.js
Labels: bug, ready for review

#84 [IN-93] Feat/in93 new matches
  backend/app.js
  backend/models/MatchesData.js
  backend/routes/api/matches.js
  client/src/components/molecules/JobPosting.js
  client/src/components/pages/Create.js
  client/src/store/actions/matchesActions.js
  client/src/store/actions/types/matchesTypes.js
Labels: feature, ready for review

#91 [IN-97] Make Delete call button in View page
  backend/app.js
  backend/routes/api/jobs.js
  backend/routes/api/users.js
  client/src/App.js
  client/src/components/molecules/Table.js
  client/src/components/pages/CreateJobPosting/TechRequirements.js
  client/src/components/pages/Prefill.js
  client/src/components/pages/Profile.js
  client/src/components/pages/View.js
  client/src/store/actions/jobPostActions.js
  client/src/store/actions/userActions.js
Labels: feature, ready for review

#94 [IN-106] Feat/in 106 matches colouring
  client/src/components/atoms/Chips.js
  client/src/components/molecules/Table.js
Labels: feature, ready for review

#96 Feat/in114 mock job posting objects
  client/src/models/templateJobDataObjects.js
Labels: feature, ready for review

#97 [IN-103] Make Home page that displays all job postings from other recruiters
  backend/models/JobPostingData.js
  backend/routes/api/jobs.js
  client/src/App.js
  client/src/assets/Home/home_asset.svg
  client/src/components/molecules/JobPosting.js
  client/src/components/molecules/Table.js
  client/src/components/molecules/ViewPosting.js
  client/src/components/molecules/index.js
  client/src/components/molecules/styles/CreateJobButton.css
  client/src/components/molecules/styles/Table.css
  client/src/components/organisms/AuthNavbar.js
  client/src/components/organisms/styles/AuthNavbar.css
  client/src/components/pages/Create.js
  client/src/components/pages/Home.js
  client/src/components/pages/styles/Home.css
  client/src/store/actions/jobPostActions.js
  client/src/store/actions/types/jobPostTypes.js
  client/src/store/reducers/jobPostingReducer.js
Labels: feature, ready for review

#95 Feat/in110 update techreqs
  client/src/components/molecules/TechStack.js
  client/src/components/molecules/styles/TechStack.css
  client/src/components/pages/Create.js
Labels: feature, ready for review

#100 Feat/in107 prefill select page
  client/src/App.js
  client/src/components/molecules/TemplatePosting.js
  client/src/components/molecules/index.js
  client/src/components/molecules/styles/TemplatePosting.css
  client/src/components/pages/Prefill.js
  client/src/components/pages/Templates.js
  client/src/components/pages/styles/Templates.css
Labels: feature, ready for review

#99 Feat/in104 nonauthorized view
  client/src/App.js
  client/src/components/pages/View.js
Labels: feature, ready for review

#93 [IN-113] Feat/in 113 view update
  backend/models/JobPostingData.js
  backend/models/MatchesData.js
  backend/routes/api/jobs.js
  backend/routes/api/matches.js
  backend/routes/api/users.js
  client/src/components/atoms/Chips.js
  client/src/components/molecules/JobPosting.js
  client/src/components/molecules/ViewFeedback.js
  client/src/components/molecules/index.js
  client/src/components/molecules/styles/ViewFeedback.css
  client/src/components/organisms/Feedback.js
  client/src/components/organisms/styles/Feedback.css
  client/src/components/pages/Create.js
  client/src/components/pages/Edit.js
  client/src/components/pages/View.js
  client/src/components/pages/styles/Create.css
  client/src/effects/filter.effects.js
Labels: feature, ready for review

#102 [IN-116] Stop firebase from re-authorizing every time we load a new page
  client/src/App.js
  client/src/components/molecules/Table.js
  client/src/components/molecules/TechStack.js
Labels: bug, ready for review

#104 [IN-102 and IN-111] Bug/in111 remove duplicate jobs
  backend/routes/api/users.js
  client/src/components/molecules/ApplicantDetails.js
  client/src/components/pages/Profile.js
  client/src/store/actions/userActions.js
  client/src/store/reducers/userReducer.js
Labels: bug, ready for review

#105 [IN-109] Fix Landing page copy
  client/package.json
  client/src/assets/Landing/circle_blue.png
  client/src/assets/Landing/circle_red.png
  client/src/assets/Landing/create-mobile.png
  client/src/assets/Landing/job_templates.svg
  client/src/assets/Landing/matches_data.svg
  client/src/assets/Landing/other-posts.png
  client/src/assets/Landing/table_asset.svg
  client/src/assets/Landing/triplets-display.png
  client/src/components/molecules/LoginForm.js
  client/src/components/molecules/RegisteredKeys.js
  client/src/components/molecules/styles/LoginForm.css
  client/src/components/organisms/Hero.js
  client/src/components/organisms/LandingCopy.js
  client/src/components/organisms/Navbar.js
  client/src/components/organisms/styles/Hero.css
  client/src/components/pages/Landing.js
  client/src/components/pages/View.js
  client/src/components/pages/styles/Landing.css
Labels: feature, ready for review

#111 Hotfix: Profile Page trigger Job Posting Table
  client/src/components/pages/Profile.js
Labels: bug, ready for review

#107 [IN-121] README documentation update
  README.md
  client/src/components/molecules/FinalReqStudents.js
  client/src/components/molecules/SeekingStudents.js
  client/src/components/molecules/TechMatchStudents.js
  client/src/components/molecules/styles/Feedback.css
  client/src/components/organisms/Feedback.js
  docs/internify_backend.pdf
  docs/prototypes/low-fi-analytics-page.PDF
  docs/prototypes/low-fi-analytics-page.jpg
  docs/prototypes/low-fi-home-page.jpg
  docs/prototypes/low-fi-home-page.pdf
  docs/prototypes/low-fi-job-create-page.jpg
  docs/prototypes/low-fi-job-create-page.pdf
  docs/student_schema.pdf
Labels: documentation, ready for review

#109 [hof-fix] aligned the names of cs concepts minor diffs btw checkbox names and student fields
  client/src/effects/filter.effects.js
  client/src/models/mockData.js
Labels: bug, ready for review

#115 [IN-125] Create legend on home page to display matches label definition
  client/src/components/atoms/Chips.js
  client/src/components/molecules/MatchesLegend.js
  client/src/components/molecules/index.js
  client/src/components/organisms/Feedback.js
  client/src/components/pages/Home.js
  client/src/components/pages/View.js
  client/src/components/pages/styles/Home.css
Labels: bug, feature, ready for review

#118 Develop merge into main
  backend/routes/api/matches.js
  client/src/components/atoms/Chips.js
  client/src/components/molecules/MatchesLegend.js
  client/src/components/molecules/index.js
  client/src/components/organisms/Feedback.js
  client/src/components/pages/Create.js
  client/src/components/pages/CreateJobPosting/ContactDetails.js
  client/src/components/pages/CreateJobPosting/CreateJobHeader.js
  client/src/components/pages/CreateJobPosting/JobDetail.js
  client/src/components/pages/CreateJobPosting/TechRequirements.js
  client/src/components/pages/Home.js
  client/src/components/pages/Prefill.js
  client/src/components/pages/Templates.js
  client/src/components/pages/View.js
  client/src/components/pages/styles/Home.css
  client/src/store/actions/jobPostActions.js
  client/src/store/actions/types/jobPostTypes.js
  client/src/store/reducers/jobPostingReducer.js
Labels: work in progress
