Repository aleemer/Internify, pull requests merged in 2021-06, with the labels that each got.

#4 Boilerplate code
  README.md
  assets/prototypes/low-fi-analytics-page.jpg
  assets/prototypes/low-fi-home-page.jpg
  assets/prototypes/low-fi-job-create-page.jpg
  internify/.gitignore
  internify/README.md
  internify/package.json
  internify/public/favicon.ico
  internify/public/index.html
  internify/public/logo192.png
  internify/public/logo512.png
  internify/public/manifest.json
  internify/public/robots.txt
  internify/src/App.css
  internify/src/App.js
  internify/src/App.test.js
  internify/src/index.css
  internify/src/index.js
  internify/src/logo.svg
  internify/src/reportWebVitals.js
  internify/src/setupTests.js
  internify/yarn.lock
Labels: documentation, enhancement

#5 Feature/atomic directories
  internify/.github/pull_request_template.md
  internify/.gitignore
  internify/package.json
  internify/public/index.html
  internify/src/App.css
  internify/src/App.js
  internify/src/components/atoms/README.md
  internify/src/components/molecules/README.md
  internify/src/components/organisms/README.md
  internify/src/components/pages/README.md
  internify/src/components/templates/README.md
Labels: documentation, enhancement

#10 [User Story 11F] - Merge Job Posting atoms
  internify/src/components/atoms/CheckBox.js
  internify/src/components/atoms/RadioBtn.js
  internify/src/components/atoms/TextFieldInput.js
Labels: enhancement

#9 [11A, 11D, 11E, 11F] - Atomic Components
  internify/src/App.css
  internify/src/App.js
  internify/src/components/atoms/Button.js
  internify/src/components/atoms/CheckBox.js
  internify/src/components/atoms/Chips.js
  internify/src/components/atoms/Icon.js
  internify/src/components/atoms/RadioBtn.js
  internify/src/components/atoms/TextFieldInput.js
  internify/src/components/molecules/Table.js
Labels: enhancement

#8 [User-Story 9b] - Job Posting Page 1
  internify/src/App.css
  internify/src/App.js
  internify/src/components/atoms/Button.js
  internify/src/components/atoms/CheckBox.js
  internify/src/components/atoms/Chips.js
  internify/src/components/atoms/Icon.js
  internify/src/components/atoms/RadioBtn.js
  internify/src/components/atoms/TextFieldInput.js
  internify/src/components/molecules/InputFormJobHeader.js
  internify/src/components/molecules/LengthSubHeader.js
  internify/src/components/molecules/PositionSubHeader.js
  internify/src/components/molecules/RadioButtonsGroup.js
  internify/src/components/molecules/Stepper.js
  internify/src/components/molecules/Table.js
  internify/src/components/molecules/styles/InputFormJobHeader.css
  internify/src/components/pages/CreateJobPosting/Create.js
  internify/src/components/pages/CreateJobPosting/styles/Create.css
Labels: enhancement

#12 refactored create classes to contain subpages
  internify/src/App.js
  internify/src/components/atoms/RadioButton.js
  internify/src/components/atoms/index.js
  internify/src/components/molecules/InputFormJobHeader.js
  internify/src/components/molecules/RadioButtonsGroup.js
  internify/src/components/molecules/Stepper.js
  internify/src/components/molecules/TechStack.js
  internify/src/components/molecules/index.js
  internify/src/components/molecules/styles/InputFormJobHeader.css
  internify/src/components/molecules/styles/TechStack.css
  internify/src/components/pages/Create.js
  internify/src/components/pages/CreateJobPosting/Create.js
  internify/src/components/pages/CreateJobPosting/CreateJobHeader.js
  internify/src/components/pages/CreateJobPosting/TechRequirements.js
  internify/src/components/pages/CreateJobPosting/styles/Create.css
  internify/src/components/pages/CreateJobPosting/styles/CreateJobHeader.css
  internify/src/components/pages/CreateJobPosting/styles/TechRequirements.css
  internify/src/components/pages/styles/Create.css
Labels: feature, ready for review

#19 12B: Refactor Landing & Login Page
  internify/src/App.js
  internify/src/components/molecules/InputFormJobHeader.js
  internify/src/components/molecules/LoginForm.js
  internify/src/components/molecules/styles/LoginForm.css
  internify/src/components/organisms/Footer.js
  internify/src/components/organisms/Hero.js
  internify/src/components/organisms/LandingCopy.js
  internify/src/components/organisms/Navbar.js
  internify/src/components/organisms/styles/Footer.css
  internify/src/components/organisms/styles/Hero.css
  internify/src/components/organisms/styles/LandingCopy.css
  internify/src/components/organisms/styles/Navbar.css
  internify/src/components/pages/Landing.js
  internify/src/components/pages/Login.js
  internify/src/components/pages/styles/Landing.css
  internify/src/components/pages/styles/Login.css
  internify/src/old-components/atoms/Button.js
  internify/src/old-components/atoms/README.md
  internify/src/old-components/atoms/styles/Button.css
  internify/src/old-components/molecules/LoginForm.js
  internify/src/old-components/molecules/README.md
  internify/src/old-components/molecules/styles/Footer.css
  internify/src/old-components/organisms/ContainerHomeGuest.js
  internify/src/old-components/organisms/FooterHomeGuest.js
  internify/src/old-components/organisms/HeaderHomeGuest.js
  internify/src/old-components/organisms/LoginBody.js
  internify/src/old-components/organisms/NavbarMain.js
  internify/src/old-components/organisms/README.md
  internify/src/old-components/organisms/styles/FooterHomeGuest.css
  internify/src/old-components/organisms/styles/LoginBody.css
  internify/src/old-components/organisms/styles/NavBarMain.css
  internify/src/old-components/pages/Landing.js
  internify/src/old-components/pages/Login.js
  internify/src/old-components/pages/README.md
Labels: bug, feature, ready for review

#20 Feat/9 e contact details
  internify/src/App.js
  internify/src/components/molecules/InputFormContactDetails.js
  internify/src/components/molecules/index.js
  internify/src/components/molecules/styles/InputFormContactDetails.css
  internify/src/components/pages/CreateJobPosting/ContactDetails.js
Labels: feature

#27 User Story 9F - Review Page
  internify/README.md
  internify/src/App.js
  internify/src/components/atoms/Button.js
  internify/src/components/molecules/JobPosting.js
  internify/src/components/molecules/RadioButtonsGroup.js
  internify/src/components/molecules/index.js
  internify/src/components/molecules/styles/JobPosting.css
  internify/src/components/organisms/AuthNavbar.js
  internify/src/components/organisms/LandingCopy.js
  internify/src/components/organisms/styles/AuthNavbar.css
  internify/src/components/organisms/styles/Navbar.css
  internify/src/components/pages/CreateJobPosting/ContactDetails.js
  internify/src/components/pages/CreateJobPosting/JobDetail.js
  internify/src/components/pages/CreateJobPosting/Review.js
  internify/src/components/pages/CreateJobPosting/styles/Review.css
  internify/src/models/mockData.js
  internify/src/store/reducers/jobPostingReducer.js
Labels: feature, ready for review

#30 Feature/score next
  internify/src/App.js
  internify/src/components/molecules/Notes.js
  internify/src/components/molecules/RegisteredKeys.js
  internify/src/components/molecules/Score.js
  internify/src/components/molecules/styles/Notes.css
  internify/src/components/organisms/Feedback.js
  internify/src/components/organisms/styles/Feedback.css
  internify/src/store/actions/jobPostActions.js
  internify/src/store/reducers/index.js
  internify/src/store/reducers/jobPostingReducer.js
  internify/src/store/reducers/studentReducer.js
Labels: feature

#31 [IN-50] Connecting the Create pages together
  internify/public/favicon.ico
  internify/public/favicon.png
  internify/public/index.html
  internify/public/logo192.png
  internify/public/logo512.png
  internify/public/manifest.json
  internify/src/App.js
  internify/src/components/atoms/MultiLineTextField.js
  internify/src/components/molecules/ApplicantDetails.js
  internify/src/components/molecules/InputFormContactDetails.js
  internify/src/components/molecules/InputFormJobHeader.js
  internify/src/components/molecules/JobPosting.js
  internify/src/components/molecules/LengthSubHeader.js
  internify/src/components/molecules/PositionSubHeader.js
  internify/src/components/molecules/RadioButtonsGroup.js
  internify/src/components/molecules/TechStack.js
  internify/src/components/pages/Create.js
  internify/src/components/pages/CreateJobPosting/ContactDetails.js
  internify/src/components/pages/CreateJobPosting/CreateJobHeader.js
  internify/src/components/pages/CreateJobPosting/JobDetail.js
  internify/src/components/pages/CreateJobPosting/Review.js
  internify/src/components/pages/CreateJobPosting/TechRequirements.js
  internify/src/components/pages/styles/Create.css
Labels: feature, ready for review
