Repository aleemer/Internify, pull requests merged in 2021-07, with the labels that each got.

#33 [IN-54] Edit Modal
  internify/src/App.js
  internify/src/components/atoms/MultiLineTextField.js
  internify/src/components/atoms/TextFieldInput.js
  internify/src/components/atoms/index.js
  internify/src/components/molecules/EditModal.js
  internify/src/components/molecules/InputFormContactDetails.js
  internify/src/components/molecules/index.js
  internify/src/components/molecules/styles/EditModal.css
  internify/src/components/molecules/styles/InputFormContactDetails.css
  internify/src/components/pages/CreateJobPosting/JobDetail.js
  internify/src/index.js
Labels: feature, ready for review

#39 [HOTFIX] updated isGpaRequired field
  internify/src/components/molecules/JobPosting.js
  internify/src/components/pages/Create.js
  internify/src/components/pages/CreateJobPosting/TechRequirements.js
Labels: bug

#41 [IN-54, IN-65] Login Authentication
  internify/package.json
  internify/public/index.html
  internify/src/App.js
  internify/src/assets/Landing/google.png
  internify/src/assets/Landing/google.svg
  internify/src/components/atoms/Button.js
  internify/src/components/atoms/index.js
  internify/src/components/molecules/LoginForm.js
  internify/src/components/organisms/AuthNavbar.js
  internify/src/components/organisms/Hero.js
  internify/src/components/organisms/styles/AuthNavbar.css
Labels: feature, ready for review

#38 [In-57] Feature/profile page
  internify/src/App.css
  internify/src/App.js
  internify/src/assets/Profile/angela_brown.png
  internify/src/components/molecules/EditModal.js
  internify/src/components/organisms/AuthNavbar.js
  internify/src/components/pages/Create.js
  internify/src/components/pages/Profile.js
  internify/src/components/pages/styles/Profile.css
Labels: feature, ready for review

#44 [IN-51] Structure three columns in Create page
  internify/src/components/atoms/index.js
  internify/src/components/molecules/styles/JobPosting.css
  internify/src/components/pages/Create.js
  internify/src/components/pages/CreateJobPosting/ContactDetails.js
  internify/src/components/pages/CreateJobPosting/CreateJobHeader.js
  internify/src/components/pages/CreateJobPosting/JobDetail.js
  internify/src/components/pages/CreateJobPosting/Review.js
  internify/src/components/pages/CreateJobPosting/TechRequirements.js
  internify/src/components/pages/CreateJobPosting/index.js
  internify/src/components/pages/styles/Create.css
Labels: feature, ready for review

#45 [IN-24] Floating Add Button
  internify/src/assets/atoms/plus-btn-icon.svg
  internify/src/components/atoms/Icon.js
  internify/src/components/molecules/CreateJobButton.js
  internify/src/components/molecules/index.js
  internify/src/components/molecules/styles/CreateJobButton.css
  internify/src/components/pages/Profile.js
Labels: feature, ready for review

#50 Feat/in 66 update footer
  internify/src/App.js
  internify/src/components/organisms/Footer.js
  internify/src/components/organisms/styles/Footer.css
Labels: feature, ready for review

#48 Feat/in67 add user resolvers
  internify/backend/app.js
  internify/backend/models/UserData.js
  internify/backend/routes/api/jobs.js
  internify/backend/routes/api/users.js
  internify/src/store/actions/studentActions.js
  internify/src/store/actions/types/userTypes.js
  internify/src/store/actions/userActions.js
  internify/src/store/reducers/index.js
  internify/src/store/reducers/studentReducer.js
  internify/src/store/reducers/userReducer.js
Labels: feature, ready for review

#46 Feat/in62 remove persis data
  internify/src/components/molecules/TechStack.js
  internify/src/components/pages/Create.js
  internify/src/store/actions/jobPostActions.js
  internify/src/store/actions/types/jobPostTypes.js
  internify/src/store/reducers/jobPostingReducer.js
Labels: bug, feature, ready for review

#47 [IN-69] Create User and POST to back-end when user logins
  internify/backend/models/StudentData.js
  internify/backend/models/UserData.js
  internify/backend/routes/api/users.js
  internify/src/App.js
  internify/src/components/molecules/JobPosting.js
  internify/src/components/molecules/LoginForm.js
  internify/src/components/molecules/Table.js
  internify/src/components/organisms/Hero.js
  internify/src/components/pages/Profile.js
  internify/src/components/pages/styles/Profile.css
  internify/src/models/mockData.js
  internify/src/store/actions/jobPostActions.js
  internify/src/store/actions/types/userTypes.js
  internify/src/store/actions/userActions.js
  internify/src/store/reducers/userReducer.js
Labels: feature, ready for review

#54 [IN-77] View-Page
  internify/src/App.js
  internify/src/components/molecules/ViewPosting.js
  internify/src/components/molecules/index.js
  internify/src/components/molecules/styles/ViewPosting.css
  internify/src/components/pages/CreateJobPosting/index.js
  internify/src/components/pages/View.js
  internify/src/components/pages/styles/View.css
  internify/src/models/mockData.js
Labels: feature, ready for review

#34 [IN-60] Dispatch hookup for matchesReducer & Feedback Component
  internify/backend/models/JobPostingData.js
  internify/src/App.js
  internify/src/components/molecules/RegisteredKeys.js
  internify/src/components/molecules/Score.js
  internify/src/components/organisms/Feedback.js
  internify/src/components/pages/Create.js
  internify/src/store/actions/jobPostActions.js
  internify/src/store/actions/types/jobPostTypes.js
  internify/src/store/reducers/jobPostingReducer.js
  internify/src/store/reducers/matchesReducer.js
Labels: feature

#56 Hotfix/css
  internify/src/App.js
  internify/src/components/organisms/Footer.js
  internify/src/components/organisms/styles/Footer.css
  internify/src/components/pages/Landing.js
  internify/src/components/pages/Login.js
  internify/src/components/pages/Profile.js
  internify/src/components/pages/styles/Login.css
  internify/src/components/pages/styles/Profile.css
Labels: bug, ready for review

#55 Feat/in76 profile pulls data
  internify/src/App.js
  internify/src/components/molecules/EditModal.js
  internify/src/components/molecules/styles/CreateJobButton.css
  internify/src/components/organisms/AuthNavbar.js
  internify/src/components/organisms/Footer.js
  internify/src/components/organisms/styles/Footer.css
  internify/src/components/pages/Create.js
  internify/src/components/pages/Landing.js
  internify/src/components/pages/Login.js
  internify/src/components/pages/Profile.js
  internify/src/components/pages/View.js
  internify/src/components/pages/styles/Login.css
  internify/src/components/pages/styles/Profile.css
Labels: feature

#58 Fix/warnings
  internify/src/App.js
  internify/src/components/organisms/styles/Navbar.css
  internify/src/components/pages/Profile.js
  internify/src/components/pages/styles/Profile.css
Labels: bug, ready for review

#62 Footer Styling Fix
  internify/src/App.js
  internify/src/components/organisms/Footer.js
  internify/src/components/organisms/styles/Footer.css
  internify/src/components/pages/Landing.js
  internify/src/components/pages/Login.js
Labels: bug, ready for review

#69 added functionality to copy to clipboard for view page
  internify/src/components/pages/View.js
Labels: feature, ready for review

#68 [IN-81/IN-87/IN-90] matchesReducer update & Notes design
  internify/backend/models/JobPostingData.js
  internify/src/components/atoms/Chips.js
  internify/src/components/molecules/ApplicantDetails.js
  internify/src/components/molecules/pages/FinalReqStudents.js
  internify/src/components/molecules/pages/SeekingStudents.js
  internify/src/components/molecules/pages/TechMatchStudents.js
  internify/src/components/molecules/pages/TotalStudents.js
  internify/src/components/molecules/pages/styles/Feedback.css
  internify/src/components/organisms/Feedback.js
  internify/src/components/organisms/styles/Feedback.css
  internify/src/components/pages/Create.js
  internify/src/components/pages/CreateJobPosting/JobDetail.js
  internify/src/store/reducers/matchesReducer.js
Labels: feature, ready for review

#66 [IN-89] Redirect Create page to View page when creating JobPosting on last step
  internify/backend/models/JobPostingData.js
  internify/backend/models/UserData.js
  internify/backend/package.json
  internify/backend/routes/api/jobs.js
  internify/backend/routes/api/users.js
  internify/src/App.js
  internify/src/components/molecules/EditModal.js
  internify/src/components/molecules/JobPosting.js
  internify/src/components/molecules/LoginForm.js
  internify/src/components/molecules/Table.js
  internify/src/components/molecules/ViewPosting.js
  internify/src/components/molecules/pages/SeekingStudents.js
  internify/src/components/molecules/pages/TechMatchStudents.js
  internify/src/components/molecules/styles/CreateJobButton.css
  internify/src/components/organisms/Feedback.js
  internify/src/components/pages/Create.js
  internify/src/components/pages/CreateJobPosting/JobDetail.js
  internify/src/components/pages/CreateJobPosting/Review.js
  internify/src/components/pages/Profile.js
  internify/src/components/pages/View.js
  internify/src/store/actions/jobPostActions.js
  internify/src/store/actions/types/jobPostTypes.js
  internify/src/store/actions/types/userTypes.js
  internify/src/store/actions/userActions.js
  internify/src/store/reducers/jobPostingReducer.js
  internify/src/store/reducers/userReducer.js
Labels: bug, feature, ready for review

#70 [IN-95] Feat/in95 redesign feedback
  internify/src/components/atoms/Chips.js
  internify/src/components/molecules/pages/FinalReqStudents.js
  internify/src/components/molecules/pages/SeekingStudents.js
  internify/src/components/molecules/pages/TechMatchStudents.js
  internify/src/components/molecules/pages/TotalStudents.js
  internify/src/components/organisms/Feedback.js
  internify/src/components/organisms/styles/Feedback.css
Labels: feature, ready for review

#67 Feat/in 83 registered keys
  internify/src/components/atoms/Chips.js
  internify/src/components/atoms/TextFieldInput.js
  internify/src/components/molecules/ApplicantDetails.js
  internify/src/components/molecules/InputFormJobHeader.js
  internify/src/components/molecules/LengthSubHeader.js
  internify/src/components/molecules/PositionSubHeader.js
  internify/src/components/molecules/RadioButtonsGroup.js
  internify/src/components/molecules/RegisteredKeys.js
  internify/src/components/molecules/TechStack.js
  internify/src/components/organisms/Feedback.js
  internify/src/components/organisms/styles/Feedback.css
  internify/src/components/pages/Create.js
  internify/src/components/pages/CreateJobPosting/CreateJobHeader.js
  internify/src/components/pages/CreateJobPosting/JobDetail.js
  internify/src/components/pages/CreateJobPosting/TechRequirements.js
  internify/src/components/pages/Profile.js
  internify/src/components/pages/styles/Create.css
  internify/src/store/actions/jobPostActions.js
  internify/src/store/actions/types/jobPostTypes.js
  internify/src/store/reducers/jobPostingReducer.js
Labels: feature, ready for review

#71 [IN-85] Export to PDF feature on View page
  internify/package.json
  internify/src/components/molecules/ViewPosting.js
Labels: feature, ready for review

#72 Feat/in 88 Prefill
  internify/src/App.js
  internify/src/assets/Prefill/prefill_empty_icon.svg
  internify/src/assets/Prefill/prefill_icon.svg
  internify/src/components/molecules/CreateJobButton.js
  internify/src/components/pages/Prefill.js
  internify/src/components/pages/View.js
  internify/src/components/pages/styles/Prefill.css
Labels: feature, ready for review

#74 [IN-96] Assign Score to JobPosting as number of matches
  internify/backend/models/JobPostingData.js
  internify/backend/routes/api/jobs.js
  internify/src/App.js
  internify/src/components/molecules/JobPosting.js
  internify/src/components/molecules/RegisteredKeys.js
  internify/src/components/molecules/Table.js
  internify/src/components/organisms/Feedback.js
  internify/src/components/pages/Create.js
  internify/src/components/pages/Profile.js
  internify/src/components/pages/View.js
  internify/src/components/pages/styles/Create.css
  internify/src/store/actions/jobPostActions.js
Labels: feature, ready for review
